plugin:
  prefix: '&c&lMURDER'
  timeLeft: 10
  lobby-world: "academy"
  min-players: 1
  max-players: 16
  map-spawn: [0, 69, 36, -180, 0]
  game-map: "builds"
messages:
  no-perm: '&cVocê não possui permissão para executar esse comando!'
  console-error: '&cVocê precisa ser um jogador para executar esse comando!'
  already-lobby: '&eVocê já está no lobby!'